### ISSUE TITLE
Problem with reading DCM images

### ISSUE THREAD

**Issue by dietzc** [scifio/scifio-bf-compat#13]
Uploaded sample name: I20140108095545_download.dcm

Problem: Images is read in as UnsignedShortType, but should be read in as ShortType.
Problems with: SCIFIO switched on in FIJI (latest updates installed).
No Problems: ImageJ/BioFormats

**Comment by hinerm** [comment]
Moving to https://github.com/scifio/scifio/issues/260 as SCIFIO has its own DICOM format.
