### ISSUE TITLE
Check for missing maven dependencies

### ISSUE THREAD

**Issue by hinerm** [scifio/scifio-bf-compat#15]
Merely adding a dependency on `scifio-bf-compat` [may not be sufficient](http://forum.imagej.net/t/cannot-open-bioformats-image/318/2) to get the Bio-Formats bridge working.

Could be missing some dependencies here..

**Comment by ctrueden** [comment]
The issue is that `scifio-bf-compat` does not depend on `formats-gpl`. Actually, I think this is good. It means we can license `scifio-bf-compat` as BSD rather than GPL; see #17 for details.
